title: TheLumberJ(h)ack
description: >-
  Trials and tribulations of a lumberj(h)ack in the infosec world.
  Breaking and sometimes building stuff, Reverse-engineering, malware
  analysis, fuzzing all the things...
baseurl: "" 
url: "https://thelumberjhack.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: thelumberjhack

avatar: "/assets/images/site/logo.png"

navbar-links:
  About me: "about"

social-network-links:
  github:  thelumberjhack
  linkedin: yannickformaggio
  email: thelumberjhack@[del-me]pm.me
  mastodon: infosec.exchange/@thelumberjhack
  rss: true

rss-description: Trials and tribulations of thelumberjhack in the infosec world

url-pretty: thelumberjhack.com

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
keywords: "reverse engineering,linux,android,aarch64,infosec,fuzzing,assembly"

link-tags: true
title-separator: " | "

timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
remote_theme: daattali/beautiful-jekyll@6.0.1
permalink: /:year-:month-:day-:title/
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
